# Default values for %REPO%.
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: jgreat/%REPO%
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
- name: docker-credentials

podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
