apiVersion: v1
kind: Service
metadata:
  name: {{ include "%REPO%.fullname" . }}
  labels:
    {{- include "%REPO%.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "%REPO%.selectorLabels" . | nindent 4 }}
